import React from "react";
import RegisterHome from "./registerHome";
export const metadata = {
  title: "Signup",
  description: "Generated by create next app",
};

const page = () => {
  return <RegisterHome />;
};

export default page;
