import React from 'react'
import Register from './register'

export const metadata = {
  title: "Signup",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Register/>
  )
}

export default page
