import React from "react";
import Login from "./login";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const Page = async ({params}) => {
 const {as} = await params
  return <Login as={as[0]}/>;
};

export default Page;
